/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Cliente.CadastroCliente;
import Cliente.EditarCliente;
import Livros.CadastroLivros;
import Livros.EditarLivro;
import Estoque.Estoque;
import Venda.Venda;
import Relatorio.Relatorio;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JInternalFrame;
import java.time.Clock;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor
 */
public class Livraria extends javax.swing.JFrame {

    /**
     * Creates new form Livraria
     */
    public Livraria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopLivraria = new javax.swing.JDesktopPane(){

            private Image image;
            {
                try {
                    image = ImageIO.read(new File("src/resources/imagemP.jpg"));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }

        };
        menuLivraria = new javax.swing.JMenuBar();
        abaCliente = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        abaLivros = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        abaRelatorios = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        abaSobre = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema kooB");
        setPreferredSize(new java.awt.Dimension(1024, 600));

        javax.swing.GroupLayout desktopLivrariaLayout = new javax.swing.GroupLayout(desktopLivraria);
        desktopLivraria.setLayout(desktopLivrariaLayout);
        desktopLivrariaLayout.setHorizontalGroup(
            desktopLivrariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        desktopLivrariaLayout.setVerticalGroup(
            desktopLivrariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        abaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Clients-icon (1).png"))); // NOI18N
        abaCliente.setText("Cliente");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Actions-user-group-new-icon.png"))); // NOI18N
        jMenuItem1.setText("Cadastrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        abaCliente.add(jMenuItem1);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Actions-user-group-properties-icon.png"))); // NOI18N
        jMenuItem3.setText("Editar Cliente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        abaCliente.add(jMenuItem3);

        menuLivraria.add(abaCliente);

        abaLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Book-icon (1).png"))); // NOI18N
        abaLivros.setText("Livro");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book-add-icon.png"))); // NOI18N
        jMenuItem4.setText("Cadastrar Livro");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        abaLivros.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book-close-icon.png"))); // NOI18N
        jMenuItem5.setText("Editar Livro");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        abaLivros.add(jMenuItem5);

        menuLivraria.add(abaLivros);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/shopping-basket-full-icon.png"))); // NOI18N
        jMenu2.setText("Venda");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/shopping-basket-add-icon (1).png"))); // NOI18N
        jMenuItem9.setText("Inicar Venda");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        menuLivraria.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Books-1-icon (1).png"))); // NOI18N
        jMenu1.setText("Estoque");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search-icon.png"))); // NOI18N
        jMenuItem6.setText("Consultar Estoque");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        menuLivraria.add(jMenu1);

        abaRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Distributor-report-icon.png"))); // NOI18N
        abaRelatorios.setText("Relatório");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search-icon.png"))); // NOI18N
        jMenuItem7.setText("Consultar Relatórios");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        abaRelatorios.add(jMenuItem7);

        menuLivraria.add(abaRelatorios);

        abaSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Actions-help-about-icon.png"))); // NOI18N
        abaSobre.setText("Sobre");
        abaSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abaSobreMouseClicked(evt);
            }
        });
        menuLivraria.add(abaSobre);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Apps-session-logout-icon.png"))); // NOI18N
        jMenu3.setText("Sair");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        menuLivraria.add(jMenu3);

        setJMenuBar(menuLivraria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopLivraria)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopLivraria)
        );

        setSize(new java.awt.Dimension(1016, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //EDITAR CLIENTES
        EditarCliente telaConsulta = new EditarCliente();
        desktopLivraria.add(telaConsulta);
        telaConsulta.setLocation(30,0);
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        //EDITAR LIVROS
        EditarLivro editarLivro = new EditarLivro();
        desktopLivraria.add(editarLivro);
        editarLivro.setLocation(30,0);
        editarLivro.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //CADASTRAR CLIENTES
        CadastroCliente telaCadastro = new CadastroCliente();
        desktopLivraria.add(telaCadastro);
        telaCadastro.setLocation(30,40);
        telaCadastro.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       //CADASTRAR LIVROS
       CadastroLivros telaLivros = new CadastroLivros();
       desktopLivraria.add(telaLivros);
       telaLivros.setLocation(30,40);
       telaLivros.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        //ESTOQUE
        Estoque estoque = new Estoque();
        desktopLivraria.add(estoque);
        estoque.setLocation(30,0);
        estoque.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        
        System.exit(0);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        //TELA DE VENDA
        Venda venda = new Venda();
        desktopLivraria.add(venda);
        venda.setLocation(30,0);
        venda.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void abaSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abaSobreMouseClicked
       //ADICIONAR SOBRE O PROGRAMA
       InformaçõesPrograma sobre = new InformaçõesPrograma();
       desktopLivraria.add(sobre);
       sobre.setLocation(30,40);
       sobre.setVisible(true);
    }//GEN-LAST:event_abaSobreMouseClicked

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        //RELATÓRIO
        Relatorio relatorio = new Relatorio();
        desktopLivraria.add(relatorio);
        relatorio.setLocation(30,0);
        relatorio.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            Livraria livraria = new Livraria();
            livraria.setLocationRelativeTo(null); //iniciar no centro!
            livraria.pack();
            livraria.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu abaCliente;
    private javax.swing.JMenu abaLivros;
    private javax.swing.JMenu abaRelatorios;
    private javax.swing.JMenu abaSobre;
    private javax.swing.JDesktopPane desktopLivraria;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuBar menuLivraria;
    // End of variables declaration//GEN-END:variables
}
